# This is considered a "typical" container Makefile an
OPS_CONF_HOME := /etc/opsfolio
OPS_CONF_DIR := /opt/opsfolio

# This is the primary JSonnet configuration file, it creates all the container's
# definition and configuration files using Jsonnet -m (multi-file) strategy.
OPSFOLIO_DEFN_JSONNET := opsfolio.jsonnet
# This file holds the list of files generated by the jsonnet --multi command
OPSFOLIO_DEFN_JSONNET_GENERATED_FILES_LIST := .opsfolio.jsonnet_generated

# All the different locations we'll look for *.jsonnet files (rightmost path wins precedence)
JSONNET_JPATH := --jpath $(OPS_CONF_HOME) --jpath $(OPS_CONF_DIR) 
generate:
	jsonnet -S $(JSONNET_JPATH) --multi . $(OPSFOLIO_DEFN_JSONNET) > $(OPSFOLIO_DEFN_JSONNET_GENERATED_FILES_LIST)
	cat $(OPSFOLIO_DEFN_JSONNET_GENERATED_FILES_LIST)  | sed 's/^\.\//  > /'
configure: generate
	   chmod 755 $(OPS_CONF_DIR)/create-opsfolio-db-and-configure-osquery.sh
	   /bin/bash $(OPS_CONF_DIR)/create-opsfolio-db-and-configure-osquery.sh  
